---
title: "riskyData-realtime data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{riskyData-realtime data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(riskyData)
```

```{r, echo = FALSE}
# bewdL <- loadAPI(
#   ID = "2001",
#   measure = "level",
#   period = 900,
#   type = "instantaneous",
#   datapoints = "range",
#   from = '2022-10-01 00:00', 
#   rtExt = TRUE)

bewdF <- loadAPI(
  ID = "2001",
  measure = "flow",
  period = 900,
  type = "instantaneous",
  datapoints = "range",
  from = '2022-10-01 00:00', 
  rtExt = TRUE)

# last data point row 36232
```


```{r}
# par(mfrow = c(2,1))
# plot(bewdL$data$dateTime, bewdL$data$value, type = 'l', main = 'Stage data for Bewdley', xlab = 'Date Time', ylab = 'Stage (m)', lwd = 2)
# abline(v = bewdL$data$dateTime[36232], col = 'red', lwd = 2)

plot(bewdF$data$dateTime, bewdF$data$value, type = 'l', main = 'Flow data for Bewdley', xlab = 'Date Time', ylab = 'Flow (m3 s-1)', lwd = 2)
abline(v = bewdF$data$dateTime[36232], col = 'red', lwd = 2)

```
